# Generated by Django 3.2.25 on 2025-04-02 17:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0003_auto_20250402_1848'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hodnoceni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hodnoceni', models.IntegerField()),
                ('komentar', models.TextField()),
                ('produkt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.product')),
                ('uzivatel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
